### PR TITLE
Rework tree, add features

### PR DESCRIPTION
**Pull request by Chaitanyabsprip**
- **refactor(kimono): replace sanitize -> tidy keyword**
- **feat(kimono): add docs and env vars to tidy cmd**

### CODE REVIEW

**Comment by rwxrob** [comment]
Is this ready but still set to draft?

**Comment by Chaitanyabsprip** [comment]
not yet complete.

**Comment by rwxrob** [comment]
Just to let you know, the Var changes are in (and Env dropped).

**Comment by Chaitanyabsprip** [comment]
Yes, I'm inculcating those changes now.

**Pull request merged**
