### PR TITLE
Add more completions, some bugfixes and added documentation.

### PR DESCRIPTION
**Pull request by Chaitanyabsprip**
- Fixed bug in `comp.Cmd`
 - Add completions for cmd names and aliases as `comp.Alias`
 - Added documentation for all completers.

### CODE REVIEW

**Comment by Chaitanyabsprip** [comment]
The tests for `comp.Cmd` were disabled (commented) and were actually failing. The output block in the test was accurate which meant the completer code had a bug. The case in question is when the `len(args) == 0`. The code returns all possible values, but ideally it would mean that the command itself hasn't been completed yet.

This made me revisit how the completion works for Cmds. The `Complete` method is always going to be called with a cmd and args. The check for length of `args` is done in the `x.detectCompletion` method. Which allows you to safely assume that `len(args) > 0` when the `Complete` method is called. So for every completer, if the `len(args) == 0` then they should either return an empty list or not bother with that case ever.

However it should be noted that the first arg can be an empty string, in which case the completer must return all possible completions.

**Comment by Chaitanyabsprip** [comment]
@rwxrob should the completers support *case insensitive* completions? For e.g. Cmd with sub-commands as "Foo", "far" and "bar", for the argument "f", the *case insensitive* completer would complete with "Foo" and "far".

**Comment by rwxrob** [comment]
As long as it is explicitly added with something like `comp.Aliases.WithIgnoreCase()`.

**Comment by Chaitanyabsprip** [comment]
I have implemented the new way of creating a Pipe of completers. Following is what the usage looks like.

```go
func ExamplePipe_Complete() {
	cmd := bonzai.Cmd{
		Name: "foo",
		Opts: `fooc|foobar|foobaz`,
		Comp: comp.Pipe{comp.Opts, filt.Prefix("foo")},
	}
	fmt.Println(cmd.Comp.Complete(cmd))
	fmt.Println(cmd.Comp.Complete(cmd, ""))
	fmt.Println(cmd.Comp.Complete(cmd, "b"))

	// Output:
	// []
	// [fooc foobar foobaz]
	// [foobar foobaz]
}
```

The implementation checks whether the element in the Pipe is a Completer or a Filter. If it is a Filter then the list of completions that has been accumulated before the filter is passed to it to process. This makes the filter a post operation. This is a limitation that makes the implementation of `filt.Prefix`, `filt.IgnoreCase` impossible. Such filters require them to be a pre operation where the input args to the `Complete` method call needs to be modified. For reference following is the implementation of WithPrefix as of this comment in this PR.

```go
func (f withPrefix) Complete(x bonzai.Cmd, args ...string) []string {
	if len(args) == 0 {
		return f.compelter.Complete(x, f.prefix)
	}
	args[0] = f.prefix + args[0]
	return f.compelter.Complete(x, args...)
}
```

Here you can see that the arguments to the `Complete` call are modified for required results. To achieve this with the new implementation, we would have to add some logic for postfix|prefix filter, which is a bit too complex that I would like it to be. I'll provide the other relevant code in the following code fold.

<details>
<summary>Relevant code for and old and new implementation</summary>

### Old Impl

```go
type withMinLen struct {
	len       int
	completer bonzai.Completer
}

// WithMinLen return a [bonzai.Completer] that limits the length of
// completions to a minimum length.
func WithMinLen(len int, completer bonzai.Completer) withMinLen {
	return withMinLen{len, completer}
}

func (f withMinLen) Complete(x bonzai.Cmd, args ...string) []string {
	var list []string
	for _, completion := range f.completer.Complete(x, args...) {
		if len(completion) >= f.len {
			list = append(list, completion)
		}
	}
	return list
}

type withPrefix struct {
	prefix    string
	compelter bonzai.Completer
}

// WithPrefix return a [bonzai.Completer] that filters completions that
// have the given prefix. This removes the requirement for the user to
// type the prefix to get complete completions.
func WithPrefix(prefix string, completer bonzai.Completer) withPrefix {
	return withPrefix{prefix, completer}
}

func (f withPrefix) Complete(x bonzai.Cmd, args ...string) []string {
	if len(args) == 0 {
		return f.compelter.Complete(x, f.prefix)
	}
	args[0] = f.prefix + args[0]
	return f.compelter.Complete(x, args...)
}
```
These are essential _Special_ completers as `Combine` is

### New Impl

```go
package comp

import (
	"github.com/rwxrob/bonzai"
)

type Filter interface {
	Filter([]string) []string
}

type Pipe []any

func (pipe Pipe) Complete(x bonzai.Cmd, args ...string) []string {
	list := make([]string, 0)
	for _, elem := range pipe {
		switch typed := elem.(type) {
		case Filter:
			list = typed.Filter(list)
		case bonzai.Completer:
			list = append(list, typed.Complete(x, args...)...)
		}
	}
	return list
}
```

```go
package filt

import "strings"

type Prefix string

func (prefix Prefix) Filter(s []string) []string {
	out := make([]string, 0)
	for _, v := range s {
		if strings.HasPrefix(v, string(prefix)) {
			out = append(out, v)
		}
	}
	return out
}

type MinLen int

func (minLen MinLen) Filter(s []string) []string {
	out := make([]string, 0)
	for _, v := range s {
		if len(v) >= int(minLen) {
			out = append(out, v)
		}
	}
	return out
}
```

#### Usage

```go
```

</details>

**Comment by rwxrob** [comment]
Let's use the same package names as I used in the `fn` package since these things are effectively the same, just only with string input. In fact, we might want to keep all of this 100% compatible with all those other transformations in `fn` since that was always the intention, to collect a library of common filters and map transformations:

- `filt`
- `mapf`

Then the `mapf.Interface` interface could just be a transformation of a single string:

```go
type Interface interface {
  Change(string) string
}
```

Also, we should probably change `filt.Filter` to `filt.Interface` to avoid stuttering.

Honestly, I think `fn/mapf.Prefix` is what we need to add and support. This stuff doesn't even belong in the comp module.

**Comment by rwxrob** [comment]
In fact, after thinking about it more. The only `comp` specific thing in `comp.Pipe` should be the `Completer` implementations, all the rest should take the form of a `fn/mapf` or an `fn/filt` so we don't get functional stuff in more than one place. I feel really strongly about that.

**Comment by rwxrob** [comment]
And I think we should standardize on some types in the `fn` package (which I will add:

- `fn.MapFunc` - `func[T any](in T) T`
- `fn.FiltFunc` - `func[T any](in []T) []T`
- `fn.Filter` - specifically a struct that implements Filter()
- `fn.Map` - specifically a struct that implements Change()

So that the type switch is consistent across all of Bonzai, more or less:

```go
func (pipe Pipe) Complete(x bonzai.Cmd, args ...string) []string {
    list := make([]string, 0)
    for _, elem := range pipe {
      switch v := elem.(type) {
      case fn.MapFunc:
        list = v.Change
      case fn.Filter:
        list = v.Filter(list)
      case fn.FilterFunc:
        list = v.Filter(list)
      case bonzai.Completer:
        list = append(list, v.Complete(x, args...)...)
      }
    }
    return list
  }
```

And can we please use `v :=` for type switches. More idiomatic to everything else.

I'm working on a PR for these changes to `fn` right now.

**Pull request merged**
